language: node_js
node_js:
  - "12"
  - "10"

cache:
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run test

after_success:
  - npm run coverage

branches:
  only:
    - master
